name: Build Liquidbounce Nextgen

on:
  push:
    branches: [ nextgen ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant all permissions for theme
        run: sudo chmod -R 777 theme
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk17
          arguments: genSources build
          gradle-version: wrapper
      - name: Upload artifact
        run: |
          function gradleprop {
              grep "${1}" gradle.properties|cut -d'=' -f2
          }
          export LB_VERSION=$(gradleprop 'mod_version')
          export MINECRAFT_VERSION=$(gradleprop 'minecraft_version')
          export LOADER_VERSION=$(gradleprop 'loader_version')
          export FABRICAPI_VERSION=$(gradleprop 'fabric_version')
          export KOTLIN_VERSION=$(gradleprop 'kotlin_version')
          export FABRIC_KOTLIN_VERSION=$(gradleprop 'fabric_kotlin_version')
          echo Version: $LB_VERSION, Minecraft: $MINECRAFT_VERSION
          cd build/libs
          export JAR=$(find . -regex '.*liquidbounce-[0-9|.]*\.jar')
          cp $JAR liquidbounce.jar
          zip -r liquidbounce.zip liquidbounce.jar ../../zip_include
          md5sum liquidbounce.zip
