name: Build LiquidBounce legacy

on:
  push:
    branches: [ legacy ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 8
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew setupCiWorkspace && ./gradlew build
      - name: Package artifact
        run: |
          cd build/libs
          cp -r ../../zip_include ./
      - name: Upload liquidbounceChina
        uses: actions/upload-artifact@v3
        with:
          name: LiquidBounceChina-legacy
          path: build/libs
