name: Build LiquidbounceChina-Nextgen

on:
  push:
    branches: [ nextgen ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant all permissions for theme
        run: sudo chmod -R 777 theme
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk17
          arguments: genSources build
          gradle-version: wrapper
      - name: Package artifact
        run: |
          cd build/libs
          export JAR=$(find . -regex '.*liquidbounce-[0-9|.]*\.jar')
          mv $JAR LiquidbounceChina-nextgen.jar
          cp -r ../../zip_include ./
      - name: Upload LiquidbounceChina
        uses: actions/upload-artifact@v3
        with:
          name: LiquidbounceChina-nextgen
          path: build/libs
