name: Build Liquidbounce Legacy

on:
  push:
    branches: [ legacy ]

jobs:
  build_1_8_9:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        env:
          mcversion: '1.8.9'
        with:
          job-id: jdk8_189
          arguments: build
          gradle-version: wrapper
      - name: Upload artifact
        run: |
          cd 1.8.9-Forge/build/libs
          export JAR=$(find . -regex '.*LiquidBounce-b[0-9|.]*\.jar')
          export LB_VERSION=$(echo $JAR | sed -r 's/.\/LiquidBounce-([a-zA-Z][0-9]+)\.jar/\1/')
          export MINECRAFT_VERSION='1.8.9'
          echo Version: $LB_VERSION, Minecraft: $MINECRAFT_VERSION
          cp $JAR liquidbounce.jar
          zip -r liquidbounce.zip liquidbounce.jar ../../zip_include
          md5sum liquidbounce.zip

  build_1_12_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        env:
          mcversion: '1.12'
        with:
          job-id: jdk8_112
          arguments: build
          gradle-version: wrapper
      - name: Upload artifact
        run: |
          cd 1.12.2-Forge/build/libs
          export JAR=$(find . -regex '.*LiquidBounce-b[0-9|.]*\.jar')
          export LB_VERSION=$(echo $JAR | sed -r 's/.\/LiquidBounce-([a-zA-Z][0-9]+)\.jar/\1/')
          export MINECRAFT_VERSION='1.12.2'
          echo Version: $LB_VERSION, Minecraft: $MINECRAFT_VERSION
          cp $JAR liquidbounce.jar
          zip -r liquidbounce.zip liquidbounce.jar ../../zip_include
          md5sum liquidbounce.zip

