name: Build LiquidBounce b72

on:
  push:
    branches: [ b72 ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 8
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload LiquidbounceChina
        uses: actions/upload-artifact@v3
        with:
          name: LiquidBounceChina-b72
          path: 1.8.9-Forge/build/libs
